version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      
mvn sonar:sonar \
  -Dsonar.projectKey=Circle-ci \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=73b873630e145abae3594990b498a38dae95834d
